<?xml version="1.0"?>
<!--
HEXAPOD VERSION 2 - CURRENT COLLISION MODEL

This file contains the collision model for the lower leg segment of the current 
generation hexapod robot.

Features simplified geometry with 3 boxes and 1 cylinder for efficient collision detection
while maintaining adequate accuracy for leg segment representation.
-->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Collision model macro for lower leg segment using optimized primitive shapes -->
    <xacro:macro name="lower_leg_collision" params="prefix position rotation">
        <!-- Parse input position string into individual coordinate components -->
        <xacro:property name="pos_parts" value="${position.split(' ')}"/>
        <xacro:property name="center_x" value="${pos_parts[0]}"/>
        <xacro:property name="center_y" value="${pos_parts[1]}"/>
        <xacro:property name="center_z" value="${pos_parts[2]}"/>
        
        <!-- Parse input rotation string into individual angle components -->
        <xacro:property name="rot_parts" value="${rotation.split(' ')}"/>
        <xacro:property name="roll" value="${rot_parts[0]}"/>
        <xacro:property name="pitch" value="${rot_parts[1]}"/>
        <xacro:property name="yaw" value="${rot_parts[2]}"/>
        
        <!-- Collision shape definitions for leg segments -->
        
        <!-- Proximal segment - main body section -->
        <xacro:property name="cube_0_size_x" value="0.0784"/>
        <xacro:property name="cube_0_size_y" value="0.0392"/>
        <xacro:property name="cube_0_size_z" value="0.0276"/>
        <xacro:property name="cube_0_offset_x" value="-0.047685"/>
        <xacro:property name="cube_0_offset_y" value="0"/>
        <xacro:property name="cube_0_offset_z" value="0.0001"/>
        <xacro:property name="cube_0_roll" value="0"/>
        <xacro:property name="cube_0_pitch" value="0"/>
        <xacro:property name="cube_0_yaw" value="0"/>
        
        <!-- Distal segment - extended body section -->
        <xacro:property name="cube_1_size_x" value="0.114"/>
        <xacro:property name="cube_1_size_y" value="0.0234"/>
        <xacro:property name="cube_1_size_z" value="0.0272"/>
        <xacro:property name="cube_1_offset_x" value="0.0404408"/> 
        <xacro:property name="cube_1_offset_y" value="-0.0001"/>
        <xacro:property name="cube_1_offset_z" value="0.0007"/>
        <xacro:property name="cube_1_roll" value="0"/>
        <xacro:property name="cube_1_pitch" value="0"/>
        <xacro:property name="cube_1_yaw" value="0"/>
        
        <!-- Terminal segment - foot connection -->
        <xacro:property name="cube_2_size_x" value="0.0352"/>
        <xacro:property name="cube_2_size_y" value="0.0118"/>
        <xacro:property name="cube_2_size_z" value="0.0378"/>
        <xacro:property name="cube_2_offset_x" value="0.0725"/>
        <xacro:property name="cube_2_offset_y" value="0"/>
        <xacro:property name="cube_2_offset_z" value="0"/>
        <xacro:property name="cube_2_roll" value="0"/>
        <xacro:property name="cube_2_pitch" value="0"/>
        <xacro:property name="cube_2_yaw" value="0"/>
        
        <!-- Joint connection element -->
        <xacro:property name="cylinder_0_radius" value="0.00925"/>
        <xacro:property name="cylinder_0_length" value="0.0392"/>
        <xacro:property name="cylinder_0_offset_x" value="-0.0894"/>
        <xacro:property name="cylinder_0_offset_y" value="-0.00005114"/>
        <xacro:property name="cylinder_0_offset_z" value="-0.0042807"/>
        <xacro:property name="cylinder_0_roll" value="1.570796327"/>
        <xacro:property name="cylinder_0_pitch" value="0"/>
        <xacro:property name="cylinder_0_yaw" value="0"/>
        
        <!-- Rotation matrix calculation for 3D coordinate transformation -->
        <xacro:property name="cr" value="${cos(roll)}"/>
        <xacro:property name="sr" value="${sin(roll)}"/>
        <xacro:property name="cp" value="${cos(pitch)}"/>
        <xacro:property name="sp" value="${sin(pitch)}"/>
        <xacro:property name="cy" value="${cos(yaw)}"/>
        <xacro:property name="sy" value="${sin(yaw)}"/>
        
        <!-- Rotation matrix elements for Rx * Ry * Rz transformation -->
        <xacro:property name="r11" value="${cy * cp}"/>
        <xacro:property name="r12" value="${cy * sp * sr - sy * cr}"/>
        <xacro:property name="r13" value="${cy * sp * cr + sy * sr}"/>
        
        <xacro:property name="r21" value="${sy * cp}"/>
        <xacro:property name="r22" value="${sy * sp * sr + cy * cr}"/>
        <xacro:property name="r23" value="${sy * sp * cr - cy * sr}"/>
        
        <xacro:property name="r31" value="${-sp}"/>
        <xacro:property name="r32" value="${cp * sr}"/>
        <xacro:property name="r33" value="${cp * cr}"/>
        
        <!-- Transform local shape positions to global coordinates -->
        <xacro:property name="cube_0_trans_x" value="${cube_0_offset_x * r11 + cube_0_offset_y * r12 + cube_0_offset_z * r13}"/>
        <xacro:property name="cube_0_trans_y" value="${cube_0_offset_x * r21 + cube_0_offset_y * r22 + cube_0_offset_z * r23}"/>
        <xacro:property name="cube_0_trans_z" value="${cube_0_offset_x * r31 + cube_0_offset_y * r32 + cube_0_offset_z * r33}"/>
        
        <xacro:property name="cube_1_trans_x" value="${cube_1_offset_x * r11 + cube_1_offset_y * r12 + cube_1_offset_z * r13}"/>
        <xacro:property name="cube_1_trans_y" value="${cube_1_offset_x * r21 + cube_1_offset_y * r22 + cube_1_offset_z * r23}"/>
        <xacro:property name="cube_1_trans_z" value="${cube_1_offset_x * r31 + cube_1_offset_y * r32 + cube_1_offset_z * r33}"/>
        
        <xacro:property name="cube_2_trans_x" value="${cube_2_offset_x * r11 + cube_2_offset_y * r12 + cube_2_offset_z * r13}"/>
        <xacro:property name="cube_2_trans_y" value="${cube_2_offset_x * r21 + cube_2_offset_y * r22 + cube_2_offset_z * r23}"/>
        <xacro:property name="cube_2_trans_z" value="${cube_2_offset_x * r31 + cube_2_offset_y * r32 + cube_2_offset_z * r33}"/>
        
        <xacro:property name="cylinder_0_trans_x" value="${cylinder_0_offset_x * r11 + cylinder_0_offset_y * r12 + cylinder_0_offset_z * r13}"/>
        <xacro:property name="cylinder_0_trans_y" value="${cylinder_0_offset_x * r21 + cylinder_0_offset_y * r22 + cylinder_0_offset_z * r23}"/>
        <xacro:property name="cylinder_0_trans_z" value="${cylinder_0_offset_x * r31 + cylinder_0_offset_y * r32 + cylinder_0_offset_z * r33}"/>
        
        <!-- Generate collision elements with transformed geometry -->
        
        <collision>
            <origin xyz="${center_x + cube_0_trans_x} ${center_y + cube_0_trans_y} ${center_z + cube_0_trans_z}" rpy="${roll + cube_0_roll} ${pitch + cube_0_pitch} ${yaw + cube_0_yaw}"/>
            <geometry>
                <box size="${cube_0_size_x} ${cube_0_size_y} ${cube_0_size_z}"/>
            </geometry>
        </collision>
        
        <collision>
            <origin xyz="${center_x + cube_1_trans_x} ${center_y + cube_1_trans_y} ${center_z + cube_1_trans_z}" rpy="${roll + cube_1_roll} ${pitch + cube_1_pitch} ${yaw + cube_1_yaw}"/>
            <geometry>
                <box size="${cube_1_size_x} ${cube_1_size_y} ${cube_1_size_z}"/>
            </geometry>
        </collision>
        
        <collision>
            <origin xyz="${center_x + cube_2_trans_x} ${center_y + cube_2_trans_y} ${center_z + cube_2_trans_z}" rpy="${roll + cube_2_roll} ${pitch + cube_2_pitch} ${yaw + cube_2_yaw}"/>
            <geometry>
                <box size="${cube_2_size_x} ${cube_2_size_y} ${cube_2_size_z}"/>
            </geometry>
        </collision>
        
        <collision>
            <origin xyz="${center_x + cylinder_0_trans_x} ${center_y + cylinder_0_trans_y} ${center_z + cylinder_0_trans_z}" rpy="${roll + cylinder_0_roll} ${pitch + cylinder_0_pitch} ${yaw + cylinder_0_yaw}"/>
            <geometry>
                <cylinder radius="${cylinder_0_radius}" length="${cylinder_0_length}"/>
            </geometry>
        </collision>
    </xacro:macro>
</robot>