<?xml version="1.0"?>
<!--
HEXAPOD VERSION 2 - MIDDLE LEG COLLISION MODEL

This file contains the collision model for the middle leg segment of the current 
generation hexapod robot.

Features optimized geometry with 1 box and 2 cylinders for efficient collision detection
while maintaining adequate accuracy. 
-->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Collision model macro for middle leg segment using primitive geometric shapes -->
    <xacro:macro name="mid_leg_collision" params="prefix position rotation">
        <!-- Parse input position string into individual coordinate components -->
        <xacro:property name="pos_parts" value="${position.split(' ')}"/>
        <xacro:property name="center_x" value="${pos_parts[0]}"/>
        <xacro:property name="center_y" value="${pos_parts[1]}"/>
        <xacro:property name="center_z" value="${pos_parts[2]}"/>
        
        <!-- Parse input rotation string into individual angle components -->
        <xacro:property name="rot_parts" value="${rotation.split(' ')}"/>
        <xacro:property name="roll" value="${rot_parts[0]}"/>
        <xacro:property name="pitch" value="${rot_parts[1]}"/>
        <xacro:property name="yaw" value="${rot_parts[2]}"/>
        
        <!-- Collision shape definitions for femur segment components -->
        
        <!-- Main body segment - central structural element -->
        <xacro:property name="cube_0_size_x" value="0.104800"/>
        <xacro:property name="cube_0_size_y" value="0.039400"/>
        <xacro:property name="cube_0_size_z" value="0.062800"/>
        <xacro:property name="cube_0_offset_x" value="-0.000123"/>
        <xacro:property name="cube_0_offset_y" value="0.000023"/>
        <xacro:property name="cube_0_offset_z" value="0.001713"/>
        <xacro:property name="cube_0_roll" value="0.000000"/>
        <xacro:property name="cube_0_pitch" value="0.000000"/>
        <xacro:property name="cube_0_yaw" value="0.000000"/>
        
        <!-- Proximal joint connection - coxa interface -->
        <xacro:property name="cylinder_0_radius" value="0.019300"/>
        <xacro:property name="cylinder_0_length" value="0.040000"/>
        <xacro:property name="cylinder_0_offset_x" value="-0.060781"/>
        <xacro:property name="cylinder_0_offset_y" value="0.000023"/>
        <xacro:property name="cylinder_0_offset_z" value="-0.005517"/>
        <xacro:property name="cylinder_0_roll" value="1.570796"/>
        <xacro:property name="cylinder_0_pitch" value="0.000000"/>
        <xacro:property name="cylinder_0_yaw" value="0.000000"/>
        
        <!-- Distal joint connection - tibia interface -->
        <xacro:property name="cylinder_1_radius" value="0.019300"/>
        <xacro:property name="cylinder_1_length" value="0.040000"/>
        <xacro:property name="cylinder_1_offset_x" value="0.060169"/>
        <xacro:property name="cylinder_1_offset_y" value="0.000023"/>
        <xacro:property name="cylinder_1_offset_z" value="-0.005517"/>
        <xacro:property name="cylinder_1_roll" value="1.570796"/>
        <xacro:property name="cylinder_1_pitch" value="0.000000"/>
        <xacro:property name="cylinder_1_yaw" value="0.000000"/>
        
        <!-- Rotation matrix calculation for 3D coordinate transformation -->
        <xacro:property name="cr" value="${cos(roll)}"/>
        <xacro:property name="sr" value="${sin(roll)}"/>
        <xacro:property name="cp" value="${cos(pitch)}"/>
        <xacro:property name="sp" value="${sin(pitch)}"/>
        <xacro:property name="cy" value="${cos(yaw)}"/>
        <xacro:property name="sy" value="${sin(yaw)}"/>
        
        <!-- Rotation matrix elements for Rx * Ry * Rz transformation -->
        <!-- First row - X-axis transformation components -->
        <xacro:property name="r11" value="${cy * cp}"/>
        <xacro:property name="r12" value="${cy * sp * sr - sy * cr}"/>
        <xacro:property name="r13" value="${cy * sp * cr + sy * sr}"/>
        
        <!-- Second row - Y-axis transformation components -->
        <xacro:property name="r21" value="${sy * cp}"/>
        <xacro:property name="r22" value="${sy * sp * sr + cy * cr}"/>
        <xacro:property name="r23" value="${sy * sp * cr - cy * sr}"/>
        
        <!-- Third row - Z-axis transformation components -->
        <xacro:property name="r31" value="${-sp}"/>
        <xacro:property name="r32" value="${cp * sr}"/>
        <xacro:property name="r33" value="${cp * cr}"/>
        
        <!-- Transform local shape positions to global coordinate system -->
        
        <!-- Main body segment transformation -->
        <xacro:property name="cube_0_trans_x" value="${cube_0_offset_x * r11 + cube_0_offset_y * r12 + cube_0_offset_z * r13}"/>
        <xacro:property name="cube_0_trans_y" value="${cube_0_offset_x * r21 + cube_0_offset_y * r22 + cube_0_offset_z * r23}"/>
        <xacro:property name="cube_0_trans_z" value="${cube_0_offset_x * r31 + cube_0_offset_y * r32 + cube_0_offset_z * r33}"/>
        
        <!-- Proximal joint transformation -->
        <xacro:property name="cylinder_0_trans_x" value="${cylinder_0_offset_x * r11 + cylinder_0_offset_y * r12 + cylinder_0_offset_z * r13}"/>
        <xacro:property name="cylinder_0_trans_y" value="${cylinder_0_offset_x * r21 + cylinder_0_offset_y * r22 + cylinder_0_offset_z * r23}"/>
        <xacro:property name="cylinder_0_trans_z" value="${cylinder_0_offset_x * r31 + cylinder_0_offset_y * r32 + cylinder_0_offset_z * r33}"/>
        
        <!-- Distal joint transformation -->
        <xacro:property name="cylinder_1_trans_x" value="${cylinder_1_offset_x * r11 + cylinder_1_offset_y * r12 + cylinder_1_offset_z * r13}"/>
        <xacro:property name="cylinder_1_trans_y" value="${cylinder_1_offset_x * r21 + cylinder_1_offset_y * r22 + cylinder_1_offset_z * r23}"/>
        <xacro:property name="cylinder_1_trans_z" value="${cylinder_1_offset_x * r31 + cylinder_1_offset_y * r32 + cylinder_1_offset_z * r33}"/>
        
        <!-- Generate collision elements with transformed geometry -->
        
        <!-- Main structural body collision -->
        <collision>
            <origin xyz="${center_x + cube_0_trans_x} ${center_y + cube_0_trans_y} ${center_z + cube_0_trans_z}" rpy="${roll + cube_0_roll} ${pitch + cube_0_pitch} ${yaw + cube_0_yaw}"/>
            <geometry>
                <box size="${cube_0_size_x} ${cube_0_size_y} ${cube_0_size_z}"/>
            </geometry>
        </collision>
        
        <!-- Proximal joint connection collision -->
        <collision>
            <origin xyz="${center_x + cylinder_0_trans_x} ${center_y + cylinder_0_trans_y} ${center_z + cylinder_0_trans_z}" rpy="${roll + cylinder_0_roll} ${pitch + cylinder_0_pitch} ${yaw + cylinder_0_yaw}"/>
            <geometry>
                <cylinder radius="${cylinder_0_radius}" length="${cylinder_0_length}"/>
            </geometry>
        </collision>
        
        <!-- Distal joint connection collision -->
        <collision>
            <origin xyz="${center_x + cylinder_1_trans_x} ${center_y + cylinder_1_trans_y} ${center_z + cylinder_1_trans_z}" rpy="${roll + cylinder_1_roll} ${pitch + cylinder_1_pitch} ${yaw + cylinder_1_yaw}"/>
            <geometry>
                <cylinder radius="${cylinder_1_radius}" length="${cylinder_1_length}"/>
            </geometry>
        </collision>
    </xacro:macro>
</robot>