<?xml version="1.0"?>
<!--
HEXAPOD VERSION 2 - FOOT TIP COLLISION MODEL

This file contains the collision model for the foot tip segment of the current 
generation hexapod robot.

Features minimal geometry with 1 sphere and 1 cylinder for efficient collision 
detection while providing adequate ground contact representation.
-->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Collision model macro for foot tip using primitive geometric shapes -->
    <xacro:macro name="tip_collision" params="prefix rotation">
        <!-- Fixed coordinate system origin for tip positioning -->
        <xacro:property name="center_x" value="0"/>
        <xacro:property name="center_y" value="0"/>
        <xacro:property name="center_z" value="0"/>
        
        <!-- Parse input rotation string into individual angle components -->
        <xacro:property name="rot_parts" value="${rotation.split(' ')}"/>
        <xacro:property name="roll" value="${rot_parts[0]}"/>
        <xacro:property name="pitch" value="${rot_parts[1]}"/>
        <xacro:property name="yaw" value="${rot_parts[2]}"/>
        
        <!-- Collision shape definitions for foot tip components -->
        
        <!-- Spherical contact element -->
        <xacro:property name="sphere_0_radius" value="0.00600"/>
        <xacro:property name="sphere_0_offset_x" value="0.0"/> <!--To simulate foot backing due to the spring change to -0.0025 -->
        <xacro:property name="sphere_0_offset_y" value="0.00000"/>
        <xacro:property name="sphere_0_offset_z" value="0.00000"/>
        <xacro:property name="sphere_0_roll" value="0.00000"/>
        <xacro:property name="sphere_0_pitch" value="0.00000"/>
        <xacro:property name="sphere_0_yaw" value="0.00000"/>
        
        <!-- Cylindrical support element -->
        <xacro:property name="cylinder_0_radius" value="0.00400"/>
        <xacro:property name="cylinder_0_length" value="0.01080"/>
        <xacro:property name="cylinder_0_offset_x" value="-0.00918"/> <!--Decrease to simulate foot backing due to the spring -->
        <xacro:property name="cylinder_0_offset_y" value="0.00000"/>
        <xacro:property name="cylinder_0_offset_z" value="0.00031"/>
        <xacro:property name="cylinder_0_roll" value="0.00000"/>
        <xacro:property name="cylinder_0_pitch" value="1.57080"/>
        <xacro:property name="cylinder_0_yaw" value="0.00000"/>
        
        <!-- Rotation matrix calculation for 3D coordinate transformation -->
        <xacro:property name="cr" value="${cos(roll)}"/>
        <xacro:property name="sr" value="${sin(roll)}"/>
        <xacro:property name="cp" value="${cos(pitch)}"/>
        <xacro:property name="sp" value="${sin(pitch)}"/>
        <xacro:property name="cy" value="${cos(yaw)}"/>
        <xacro:property name="sy" value="${sin(yaw)}"/>
        
        <!-- Rotation matrix elements for Rx * Ry * Rz transformation -->
        <xacro:property name="r11" value="${cy * cp}"/>
        <xacro:property name="r12" value="${cy * sp * sr - sy * cr}"/>
        <xacro:property name="r13" value="${cy * sp * cr + sy * sr}"/>
        
        <xacro:property name="r21" value="${sy * cp}"/>
        <xacro:property name="r22" value="${sy * sp * sr + cy * cr}"/>
        <xacro:property name="r23" value="${sy * sp * cr - cy * sr}"/>
        
        <xacro:property name="r31" value="${-sp}"/>
        <xacro:property name="r32" value="${cp * sr}"/>
        <xacro:property name="r33" value="${cp * cr}"/>
        
        <!-- Transform local shape positions to global coordinate system -->
        <xacro:property name="sphere_0_trans_x" value="${sphere_0_offset_x * r11 + sphere_0_offset_y * r12 + sphere_0_offset_z * r13}"/>
        <xacro:property name="sphere_0_trans_y" value="${sphere_0_offset_x * r21 + sphere_0_offset_y * r22 + sphere_0_offset_z * r23}"/>
        <xacro:property name="sphere_0_trans_z" value="${sphere_0_offset_x * r31 + sphere_0_offset_y * r32 + sphere_0_offset_z * r33}"/>
        
        <xacro:property name="cylinder_0_trans_x" value="${cylinder_0_offset_x * r11 + cylinder_0_offset_y * r12 + cylinder_0_offset_z * r13}"/>
        <xacro:property name="cylinder_0_trans_y" value="${cylinder_0_offset_x * r21 + cylinder_0_offset_y * r22 + cylinder_0_offset_z * r23}"/>
        <xacro:property name="cylinder_0_trans_z" value="${cylinder_0_offset_x * r31 + cylinder_0_offset_y * r32 + cylinder_0_offset_z * r33}"/>
        
        <!-- Generate collision elements with transformed geometry -->
        <collision>
            <origin xyz="${center_x + sphere_0_trans_x} ${center_y + sphere_0_trans_y} ${center_z + sphere_0_trans_z}" rpy="${roll + sphere_0_roll} ${pitch + sphere_0_pitch} ${yaw + sphere_0_yaw}"/>
            <geometry>
                <sphere radius="${sphere_0_radius}"/>
            </geometry>
        </collision>
        
        <collision>
            <origin xyz="${center_x + cylinder_0_trans_x} ${center_y + cylinder_0_trans_y} ${center_z + cylinder_0_trans_z}" rpy="${roll + cylinder_0_roll} ${pitch + cylinder_0_pitch} ${yaw + cylinder_0_yaw}"/>
            <geometry>
                <cylinder radius="${cylinder_0_radius}" length="${cylinder_0_length}"/>
            </geometry>
        </collision>
    </xacro:macro>
</robot>