<?xml version="1.0"?>
<!--
HEXAPOD VERSION 2 - UPPER LEG COLLISION MODEL

This file contains the collision model for the upper leg segment of the current 
generation hexapod robot.

Features comprehensive geometry with 3 boxes and 4 cylinders for detailed collision 
detection.
-->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Collision model macro for upper leg segment using multiple primitive geometric shapes -->
    <xacro:macro name="upper_leg_collision" params="prefix position rotation">
        <!-- Parse input position string into individual coordinate components -->
        <xacro:property name="pos_parts" value="${position.split(' ')}"/>
        <xacro:property name="center_x" value="${pos_parts[0]}"/>
        <xacro:property name="center_y" value="${pos_parts[1]}"/>
        <xacro:property name="center_z" value="${pos_parts[2]}"/>
        
        <!-- Parse input rotation string into individual angle components -->
        <xacro:property name="rot_parts" value="${rotation.split(' ')}"/>
        <xacro:property name="roll" value="${rot_parts[0]}"/>
        <xacro:property name="pitch" value="${rot_parts[1]}"/>
        <xacro:property name="yaw" value="${rot_parts[2]}"/>
        
        <!-- Collision shape definitions for coxa segment components -->
        
        <!-- Box elements -->
        <xacro:property name="cube_0_size_x" value="0.022"/>
        <xacro:property name="cube_0_size_y" value="0.0316"/>
        <xacro:property name="cube_0_size_z" value="0.0282"/>
        <xacro:property name="cube_0_offset_x" value="0.00682"/>
        <xacro:property name="cube_0_offset_y" value="-0.00061"/>
        <xacro:property name="cube_0_offset_z" value="-0.00009"/>
        <xacro:property name="cube_0_roll" value="0.00000"/>
        <xacro:property name="cube_0_pitch" value="0.00000"/>
        <xacro:property name="cube_0_yaw" value="0.00000"/>
        
        <xacro:property name="cube_1_size_x" value="0.036"/>
        <xacro:property name="cube_1_size_y" value="0.004"/>
        <xacro:property name="cube_1_size_z" value="0.036"/>
        <xacro:property name="cube_1_offset_x" value="0.02101"/>
        <xacro:property name="cube_1_offset_y" value="-0.01767"/>
        <xacro:property name="cube_1_offset_z" value="-0.00009"/>
        <xacro:property name="cube_1_roll" value="0.00000"/>
        <xacro:property name="cube_1_pitch" value="0.00000"/>
        <xacro:property name="cube_1_yaw" value="0.00000"/>
        
        <xacro:property name="cube_2_size_x" value="0.036"/>
        <xacro:property name="cube_2_size_y" value="0.004"/>
        <xacro:property name="cube_2_size_z" value="0.036"/>
        <xacro:property name="cube_2_offset_x" value="0.02101"/>
        <xacro:property name="cube_2_offset_y" value="0.01819"/>
        <xacro:property name="cube_2_offset_z" value="-0.00009"/>
        <xacro:property name="cube_2_roll" value="0.00000"/>
        <xacro:property name="cube_2_pitch" value="0.00000"/>
        <xacro:property name="cube_2_yaw" value="0.00000"/>
        
        <!-- Cylindrical elements -->
        <xacro:property name="cylinder_0_radius" value="0.014"/>
        <xacro:property name="cylinder_0_length" value="0.0306"/>
        <xacro:property name="cylinder_0_offset_x" value="-0.01931"/>
        <xacro:property name="cylinder_0_offset_y" value="0.00014"/>
        <xacro:property name="cylinder_0_offset_z" value="-0.00009"/>
        <xacro:property name="cylinder_0_roll" value="0.00000"/>
        <xacro:property name="cylinder_0_pitch" value="0.00000"/>
        <xacro:property name="cylinder_0_yaw" value="0.00000"/>
        
        <xacro:property name="cylinder_1_radius" value="0.026"/>
        <xacro:property name="cylinder_1_length" value="0.0082"/>
        <xacro:property name="cylinder_1_offset_x" value="-0.01930"/>
        <xacro:property name="cylinder_1_offset_y" value="0.00026"/>
        <xacro:property name="cylinder_1_offset_z" value="-0.00009"/>
        <xacro:property name="cylinder_1_roll" value="0.00000"/>
        <xacro:property name="cylinder_1_pitch" value="0.00000"/>
        <xacro:property name="cylinder_1_yaw" value="0.00000"/>
        
        <xacro:property name="cylinder_2_radius" value="0.018"/>
        <xacro:property name="cylinder_2_length" value="0.004"/>
        <xacro:property name="cylinder_2_offset_x" value="0.03952"/>
        <xacro:property name="cylinder_2_offset_y" value="-0.01767"/>
        <xacro:property name="cylinder_2_offset_z" value="0.00017"/>
        <xacro:property name="cylinder_2_roll" value="1.57080"/>
        <xacro:property name="cylinder_2_pitch" value="0.00000"/>
        <xacro:property name="cylinder_2_yaw" value="0.00000"/>
        
        <xacro:property name="cylinder_3_radius" value="0.018"/>
        <xacro:property name="cylinder_3_length" value="0.004"/>
        <xacro:property name="cylinder_3_offset_x" value="0.03952"/>
        <xacro:property name="cylinder_3_offset_y" value="0.01819"/>
        <xacro:property name="cylinder_3_offset_z" value="0.00017"/>
        <xacro:property name="cylinder_3_roll" value="1.57080"/>
        <xacro:property name="cylinder_3_pitch" value="0.00000"/>
        <xacro:property name="cylinder_3_yaw" value="0.00000"/>
        
        <!-- Rotation matrix calculation for 3D coordinate transformation -->
        <xacro:property name="cr" value="${cos(roll)}"/>
        <xacro:property name="sr" value="${sin(roll)}"/>
        <xacro:property name="cp" value="${cos(pitch)}"/>
        <xacro:property name="sp" value="${sin(pitch)}"/>
        <xacro:property name="cy" value="${cos(yaw)}"/>
        <xacro:property name="sy" value="${sin(yaw)}"/>
        
        <!-- Rotation matrix elements for Rx * Ry * Rz transformation -->
        <xacro:property name="r11" value="${cy * cp}"/>
        <xacro:property name="r12" value="${cy * sp * sr - sy * cr}"/>
        <xacro:property name="r13" value="${cy * sp * cr + sy * sr}"/>
        
        <xacro:property name="r21" value="${sy * cp}"/>
        <xacro:property name="r22" value="${sy * sp * sr + cy * cr}"/>
        <xacro:property name="r23" value="${sy * sp * cr - cy * sr}"/>
        
        <xacro:property name="r31" value="${-sp}"/>
        <xacro:property name="r32" value="${cp * sr}"/>
        <xacro:property name="r33" value="${cp * cr}"/>
        
        <!-- Transform local shape positions to global coordinate system -->
        <xacro:property name="cube_0_trans_x" value="${cube_0_offset_x * r11 + cube_0_offset_y * r12 + cube_0_offset_z * r13}"/>
        <xacro:property name="cube_0_trans_y" value="${cube_0_offset_x * r21 + cube_0_offset_y * r22 + cube_0_offset_z * r23}"/>
        <xacro:property name="cube_0_trans_z" value="${cube_0_offset_x * r31 + cube_0_offset_y * r32 + cube_0_offset_z * r33}"/>
        
        <xacro:property name="cube_1_trans_x" value="${cube_1_offset_x * r11 + cube_1_offset_y * r12 + cube_1_offset_z * r13}"/>
        <xacro:property name="cube_1_trans_y" value="${cube_1_offset_x * r21 + cube_1_offset_y * r22 + cube_1_offset_z * r23}"/>
        <xacro:property name="cube_1_trans_z" value="${cube_1_offset_x * r31 + cube_1_offset_y * r32 + cube_1_offset_z * r33}"/>
        
        <xacro:property name="cube_2_trans_x" value="${cube_2_offset_x * r11 + cube_2_offset_y * r12 + cube_2_offset_z * r13}"/>
        <xacro:property name="cube_2_trans_y" value="${cube_2_offset_x * r21 + cube_2_offset_y * r22 + cube_2_offset_z * r23}"/>
        <xacro:property name="cube_2_trans_z" value="${cube_2_offset_x * r31 + cube_2_offset_y * r32 + cube_2_offset_z * r33}"/>
        
        <xacro:property name="cylinder_0_trans_x" value="${cylinder_0_offset_x * r11 + cylinder_0_offset_y * r12 + cylinder_0_offset_z * r13}"/>
        <xacro:property name="cylinder_0_trans_y" value="${cylinder_0_offset_x * r21 + cylinder_0_offset_y * r22 + cylinder_0_offset_z * r23}"/>
        <xacro:property name="cylinder_0_trans_z" value="${cylinder_0_offset_x * r31 + cylinder_0_offset_y * r32 + cylinder_0_offset_z * r33}"/>
        
        <xacro:property name="cylinder_1_trans_x" value="${cylinder_1_offset_x * r11 + cylinder_1_offset_y * r12 + cylinder_1_offset_z * r13}"/>
        <xacro:property name="cylinder_1_trans_y" value="${cylinder_1_offset_x * r21 + cylinder_1_offset_y * r22 + cylinder_1_offset_z * r23}"/>
        <xacro:property name="cylinder_1_trans_z" value="${cylinder_1_offset_x * r31 + cylinder_1_offset_y * r32 + cylinder_1_offset_z * r33}"/>
        
        <xacro:property name="cylinder_2_trans_x" value="${cylinder_2_offset_x * r11 + cylinder_2_offset_y * r12 + cylinder_2_offset_z * r13}"/>
        <xacro:property name="cylinder_2_trans_y" value="${cylinder_2_offset_x * r21 + cylinder_2_offset_y * r22 + cylinder_2_offset_z * r23}"/>
        <xacro:property name="cylinder_2_trans_z" value="${cylinder_2_offset_x * r31 + cylinder_2_offset_y * r32 + cylinder_2_offset_z * r33}"/>
        
        <xacro:property name="cylinder_3_trans_x" value="${cylinder_3_offset_x * r11 + cylinder_3_offset_y * r12 + cylinder_3_offset_z * r13}"/>
        <xacro:property name="cylinder_3_trans_y" value="${cylinder_3_offset_x * r21 + cylinder_3_offset_y * r22 + cylinder_3_offset_z * r23}"/>
        <xacro:property name="cylinder_3_trans_z" value="${cylinder_3_offset_x * r31 + cylinder_3_offset_y * r32 + cylinder_3_offset_z * r33}"/>
        
        <!-- Generate collision elements with transformed geometry -->
        <collision>
            <origin xyz="${center_x + cube_0_trans_x} ${center_y + cube_0_trans_y} ${center_z + cube_0_trans_z}" rpy="${roll + cube_0_roll} ${pitch + cube_0_pitch} ${yaw + cube_0_yaw}"/>
            <geometry>
                <box size="${cube_0_size_x} ${cube_0_size_y} ${cube_0_size_z}"/>
            </geometry>
        </collision>
        
        <collision>
            <origin xyz="${center_x + cube_1_trans_x} ${center_y + cube_1_trans_y} ${center_z + cube_1_trans_z}" rpy="${roll + cube_1_roll} ${pitch + cube_1_pitch} ${yaw + cube_1_yaw}"/>
            <geometry>
                <box size="${cube_1_size_x} ${cube_1_size_y} ${cube_1_size_z}"/>
            </geometry>
        </collision>
        
        <collision>
            <origin xyz="${center_x + cube_2_trans_x} ${center_y + cube_2_trans_y} ${center_z + cube_2_trans_z}" rpy="${roll + cube_2_roll} ${pitch + cube_2_pitch} ${yaw + cube_2_yaw}"/>
            <geometry>
                <box size="${cube_2_size_x} ${cube_2_size_y} ${cube_2_size_z}"/>
            </geometry>
        </collision>
        
        <collision>
            <origin xyz="${center_x + cylinder_0_trans_x} ${center_y + cylinder_0_trans_y} ${center_z + cylinder_0_trans_z}" rpy="${roll + cylinder_0_roll} ${pitch + cylinder_0_pitch} ${yaw + cylinder_0_yaw}"/>
            <geometry>
                <cylinder radius="${cylinder_0_radius}" length="${cylinder_0_length}"/>
            </geometry>
        </collision>
        
        <collision>
            <origin xyz="${center_x + cylinder_1_trans_x} ${center_y + cylinder_1_trans_y} ${center_z + cylinder_1_trans_z}" rpy="${roll + cylinder_1_roll} ${pitch + cylinder_1_pitch} ${yaw + cylinder_1_yaw}"/>
            <geometry>
                <cylinder radius="${cylinder_1_radius}" length="${cylinder_1_length}"/>
            </geometry>
        </collision>
        
        <collision>
            <origin xyz="${center_x + cylinder_2_trans_x} ${center_y + cylinder_2_trans_y} ${center_z + cylinder_2_trans_z}" rpy="${roll + cylinder_2_roll} ${pitch + cylinder_2_pitch} ${yaw + cylinder_2_yaw}"/>
            <geometry>
                <cylinder radius="${cylinder_2_radius}" length="${cylinder_2_length}"/>
            </geometry>
        </collision>
        
        <collision>
            <origin xyz="${center_x + cylinder_3_trans_x} ${center_y + cylinder_3_trans_y} ${center_z + cylinder_3_trans_z}" rpy="${roll + cylinder_3_roll} ${pitch + cylinder_3_pitch} ${yaw + cylinder_3_yaw}"/>
            <geometry>
                <cylinder radius="${cylinder_3_radius}" length="${cylinder_3_length}"/>
            </geometry>
        </collision>
    </xacro:macro>
</robot>