# ros2_control config for hexapod robot.
#
# Defines:
# - controller_manager: main controller manager (100 Hz).
# - legX_controller (X=1..6): JointTrajectoryControllers for each leg (3 joints each).
# - joint_state_broadcaster: publishes joint states.
# - imu_broadcaster: broadcasts data from the IMU sensor.
#
# Enables smooth leg control and sensor feedback.

# Controller manager configuration
controller_manager:
  ros__parameters:
    update_rate: 100  # Controller update frequency in Hz

    # Registration of trajectory controllers for each hexapod leg
    leg1_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    leg2_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    leg3_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    leg4_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    leg5_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    leg6_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # Registration of the joint state broadcaster,
    # which publishes the current positions and velocities of all joints
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    imu_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster
      sensor_name: imu

# Configuration for each individual hexapod leg controller

# Controller for leg 1
leg1_controller:
  ros__parameters:
    joints:
      - joint1_1
      - joint2_1
      - joint3_1
    command_interfaces:
      - position  # Controller sends position commands
    state_interfaces:
      - position  # Reads current joint position
      - velocity  # Reads current joint velocity
    allow_nonzero_velocity_at_trajectory_end: true # Allow non-zero end velocity

# Controller for leg 2
leg2_controller:
  ros__parameters:
    joints:
      - joint1_2
      - joint2_2
      - joint3_2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true

# Controller for leg 3
leg3_controller:
  ros__parameters:
    joints:
      - joint1_3
      - joint2_3
      - joint3_3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true

# Controller for leg 4
leg4_controller:
  ros__parameters:
    joints:
      - joint1_4
      - joint2_4
      - joint3_4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true

# Controller for leg 5
leg5_controller:
  ros__parameters:
    joints:
      - joint1_5
      - joint2_5
      - joint3_5
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true

# Controller for leg 6
leg6_controller:
  ros__parameters:
    joints:
      - joint1_6
      - joint2_6
      - joint3_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true

