<?xml version="1.0"?>
<!--
HEXAPOD VERSION 1 (DEPRECATED)

This file contains the collision model for the lower leg segment of the first 
generation hexapod robot. This version is no longer supported and maintained.
Current hexapod implementations use version 2 collision models.

Note: This file is kept for reference only.
-->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Collision model macro for lower leg segment using primitive geometric shapes -->
    <xacro:macro name="lower_leg_collision" params="prefix position rotation">
        <!-- Parse input position string into individual coordinate components -->
        <xacro:property name="pos_parts" value="${position.split(' ')}"/>
        <xacro:property name="center_x" value="${pos_parts[0]}"/>
        <xacro:property name="center_y" value="${pos_parts[1]}"/>
        <xacro:property name="center_z" value="${pos_parts[2]}"/>
        
        <!-- Parse input rotation string into individual angle components -->
        <xacro:property name="rot_parts" value="${rotation.split(' ')}"/>
        <xacro:property name="roll" value="${rot_parts[0]}"/>
        <xacro:property name="pitch" value="${rot_parts[1]}"/>
        <xacro:property name="yaw" value="${rot_parts[2]}"/>
        
        <!-- Collision shape definitions based on exported CSV data from 3D modeling -->
        <xacro:property name="cube_1_size_x" value="0.022"/>
        <xacro:property name="cube_1_size_y" value="0.1206"/>
        <xacro:property name="cube_1_size_z" value="0.0312"/>
        <xacro:property name="cube_1_offset_x" value="-0.00035798"/>
        <xacro:property name="cube_1_offset_y" value="0.0256533"/>
        <xacro:property name="cube_1_offset_z" value="0.0"/>
        
        <xacro:property name="cube_2_size_x" value="0.03"/>
        <xacro:property name="cube_2_size_y" value="0.046"/>
        <xacro:property name="cube_2_size_z" value="0.0312"/>
        <xacro:property name="cube_2_offset_x" value="-0.00034352"/>
        <xacro:property name="cube_2_offset_y" value="-0.0574041"/>
        <xacro:property name="cube_2_offset_z" value="0.0"/>
        
        <!-- Joint connection - cylindrical shape -->
        <xacro:property name="cylinder_1_radius" value="0.00425"/>
        <xacro:property name="cylinder_1_length" value="0.0130"/>
        <xacro:property name="cylinder_1_offset_x" value="-0.00025391"/>
        <xacro:property name="cylinder_1_offset_y" value="0.0926495"/>
        <xacro:property name="cylinder_1_offset_z" value="0.0"/>
        
        <!-- End effector - spherical shape -->
        <xacro:property name="sphere_1_radius" value="0.00425"/>
        <xacro:property name="sphere_1_offset_x" value="-0.00025391"/>
        <xacro:property name="sphere_1_offset_y" value="0.0992194"/>
        <xacro:property name="sphere_1_offset_z" value="0.0"/>
        
        <!-- Rotation matrix calculation for 3D coordinate transformation -->
        <xacro:property name="cr" value="${cos(roll)}"/>
        <xacro:property name="sr" value="${sin(roll)}"/>
        <xacro:property name="cp" value="${cos(pitch)}"/>
        <xacro:property name="sp" value="${sin(pitch)}"/>
        <xacro:property name="cy" value="${cos(yaw)}"/>
        <xacro:property name="sy" value="${sin(yaw)}"/>
        
        <!-- Rotation matrix elements for Rx * Ry * Rz transformation -->
        <xacro:property name="r11" value="${cy * cp}"/>
        <xacro:property name="r12" value="${cy * sp * sr - sy * cr}"/>
        <xacro:property name="r13" value="${cy * sp * cr + sy * sr}"/>
        
        <xacro:property name="r21" value="${sy * cp}"/>
        <xacro:property name="r22" value="${sy * sp * sr + cy * cr}"/>
        <xacro:property name="r23" value="${sy * sp * cr - cy * sr}"/>
        
        <xacro:property name="r31" value="${-sp}"/>
        <xacro:property name="r32" value="${cp * sr}"/>
        <xacro:property name="r33" value="${cp * cr}"/>
        
        <!-- Transform local shape positions to global coordinates -->
        <xacro:property name="cube_1_trans_x" value="${cube_1_offset_x * r11 + cube_1_offset_y * r12 + cube_1_offset_z * r13}"/>
        <xacro:property name="cube_1_trans_y" value="${cube_1_offset_x * r21 + cube_1_offset_y * r22 + cube_1_offset_z * r23}"/>
        <xacro:property name="cube_1_trans_z" value="${cube_1_offset_x * r31 + cube_1_offset_y * r32 + cube_1_offset_z * r33}"/>
        
        <xacro:property name="cube_2_trans_x" value="${cube_2_offset_x * r11 + cube_2_offset_y * r12 + cube_2_offset_z * r13}"/>
        <xacro:property name="cube_2_trans_y" value="${cube_2_offset_x * r21 + cube_2_offset_y * r22 + cube_2_offset_z * r23}"/>
        <xacro:property name="cube_2_trans_z" value="${cube_2_offset_x * r31 + cube_2_offset_y * r32 + cube_2_offset_z * r33}"/>
        
        <!-- Joint connection transformation -->
        <xacro:property name="cylinder_1_trans_x" value="${cylinder_1_offset_x * r11 + cylinder_1_offset_y * r12 + cylinder_1_offset_z * r13}"/>
        <xacro:property name="cylinder_1_trans_y" value="${cylinder_1_offset_x * r21 + cylinder_1_offset_y * r22 + cylinder_1_offset_z * r23}"/>
        <xacro:property name="cylinder_1_trans_z" value="${cylinder_1_offset_x * r31 + cylinder_1_offset_y * r32 + cylinder_1_offset_z * r33}"/>
        
        <!-- End effector transformation -->
        <xacro:property name="sphere_1_trans_x" value="${sphere_1_offset_x * r11 + sphere_1_offset_y * r12 + sphere_1_offset_z * r13}"/>
        <xacro:property name="sphere_1_trans_y" value="${sphere_1_offset_x * r21 + sphere_1_offset_y * r22 + sphere_1_offset_z * r23}"/>
        <xacro:property name="sphere_1_trans_z" value="${sphere_1_offset_x * r31 + sphere_1_offset_y * r32 + sphere_1_offset_z * r33}"/>
        
        <!-- Generate collision elements with transformed geometry -->
                <collision>
            <origin xyz="${center_x + cube_1_trans_x} ${center_y + cube_1_trans_y} ${center_z + cube_1_trans_z}" rpy="${roll} ${pitch} ${yaw}"/>
            <geometry>
                <box size="${cube_1_size_x} ${cube_1_size_y} ${cube_1_size_z}"/>
            </geometry>
        </collision>
        
        <collision>
            <origin xyz="${center_x + cube_2_trans_x} ${center_y + cube_2_trans_y} ${center_z + cube_2_trans_z}" rpy="${roll} ${pitch} ${yaw}"/>
            <geometry>
                <box size="${cube_2_size_x} ${cube_2_size_y} ${cube_2_size_z}"/>
            </geometry>
        </collision>
        
        <!-- Joint connection collision cylinder -->
        <collision>
            <origin xyz="${center_x + cylinder_1_trans_x} ${center_y + cylinder_1_trans_y} ${center_z + cylinder_1_trans_z}" rpy="${roll + 1.570796327} ${pitch} ${yaw}"/>
            <geometry>
                <cylinder radius="${cylinder_1_radius}" length="${cylinder_1_length}"/>
            </geometry>
        </collision>
        
        <!-- End effector collision sphere -->
        <collision>
            <origin xyz="${center_x + sphere_1_trans_x} ${center_y + sphere_1_trans_y} ${center_z + sphere_1_trans_z}" rpy="${roll} ${pitch} ${yaw}"/>
            <geometry>
                <sphere radius="${sphere_1_radius}"/>
            </geometry>
        </collision>
    </xacro:macro>
</robot>